### ISSUE TITLE
FE code review

### ISSUE THREAD

**Issue by hurricanenara** [refido/Kashier-Krusty-Krab#6]
good job! leaving a couple of comments below -- let me know if you have any questions! :)

1. we should avoid in-line styles! keep these stylings in the css file to separate concerns
https://github.com/refido/Kashier-Krusty-Krab/blob/05e3d37293dcffae518acfdce5a1e08a85458ab7/src/components/DefaultLayout.js#L24-L26

2. great job using the `try...catch` block! and we should wrap `handleSubmit` in `useCallback` -- i suggest you look into how it's used and when to use it (hint: it involves memoizing & therefore increases component performance)
https://github.com/refido/Kashier-Krusty-Krab/blob/05e3d37293dcffae518acfdce5a1e08a85458ab7/src/components/FormLogin.js#L15-L27

3. there's a lot of in-line styling in this file, let's move them into a single css file & import them
https://github.com/refido/Kashier-Krusty-Krab/blob/05e3d37293dcffae518acfdce5a1e08a85458ab7/src/components/SidebarMenu.js#L22

4. even though this is mock data, it would be helpful to see a variety of values that could potentially show on a user's screen -- also images could be a headache sometimes so using mock images would be good to test out how images would fit to the overall design
https://github.com/refido/Kashier-Krusty-Krab/blob/05e3d37293dcffae518acfdce5a1e08a85458ab7/src/pages/Homepage.js#L7

5. i'm curious how the team decided to use both styled components and pure css -- it's important to choose one and keep it consistent throughout the codebase!
https://github.com/refido/Kashier-Krusty-Krab/blob/05e3d37293dcffae518acfdce5a1e08a85458ab7/src/pages/Login.js#L17

6. `row` doesn't seem to be a valid css value for the `justify-content` property - could you double check this?
https://github.com/refido/Kashier-Krusty-Krab/blob/05e3d37293dcffae518acfdce5a1e08a85458ab7/src/styles/LoginForm.css#L14

7. there's a good amount of share properties  between these two selectors, let's combine what can be shared
https://github.com/refido/Kashier-Krusty-Krab/blob/05e3d37293dcffae518acfdce5a1e08a85458ab7/src/styles/LoginForm.css#L32-L52

**Comment by refido** [comment]
Okay thanks for the review, the issue will be revised in the next pull request.
